#!/usr/bin/env python
import os

header = 'Content-Type:text/html\n\n'

form = os.environ["QUERY_STRING"]
username = form.split("&")[0].split("=")[1]
whattodo = form.split("&")[1].split("=")[1]

print "<html>"
print "<head>"
print "<title>Doc. Produit par un CGI</title>"
print "</head>"
print "<body>"
print "<h2>CGI Script Output </h2>"
print "<p> Username = %s" % username
print "<p> WhatTodo = %s" % whattodo
print "</body>"
print "</html>"